# Generated by Django 4.2.5 on 2023-10-27 22:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trans_comm', '0003_delete_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worksAt', models.CharField(max_length=255)),
                ('livesIn', models.CharField(max_length=255)),
                ('whereFrom', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('profilePic', models.FileField(blank=True, null=True, upload_to='media/photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'pdf'])])),
                ('bannerPic', models.FileField(blank=True, null=True, upload_to='media/photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'pdf'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
