# Generated by Django 4.1.5 on 2023-01-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('public_profile', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('details', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.company')),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('rehearsal_start', models.DateField()),
                ('show_open', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.company')),
                ('director_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getdata.performers')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('performer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='getdata.performers')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.shows')),
            ],
        ),
        migrations.CreateModel(
            name='RehearsalVenues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('location', models.CharField(max_length=128, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.company')),
            ],
        ),
        migrations.CreateModel(
            name='Conflicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('performer_id', models.ManyToManyField(to='getdata.performers')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='performers',
            field=models.ManyToManyField(blank=True, to='getdata.performers'),
        ),
        migrations.CreateModel(
            name='CallTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.company')),
                ('performers', models.ManyToManyField(to='getdata.performers')),
                ('show_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.shows')),
                ('venue_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='getdata.rehearsalvenues')),
            ],
        ),
    ]
