# Generated by Django 4.1.5 on 2023-01-19 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('performer_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='getdata.performers')),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('rehearsal_start', models.DateTimeField()),
                ('show_open', models.DateTimeField()),
                ('director_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='getdata.performers')),
            ],
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_name', models.CharField(max_length=128, unique=True)),
                ('role', models.ManyToManyField(to='getdata.roles')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.shows')),
            ],
        ),
        migrations.AddField(
            model_name='roles',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.shows'),
        ),
        migrations.CreateModel(
            name='RehearsalVenues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('location', models.CharField(max_length=128, unique=True)),
                ('show_id', models.ManyToManyField(to='getdata.shows')),
            ],
        ),
        migrations.CreateModel(
            name='Conflicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('performer_id', models.ManyToManyField(to='getdata.performers')),
            ],
        ),
        migrations.CreateModel(
            name='CallTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('performers', models.ManyToManyField(to='getdata.performers')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.shows')),
            ],
        ),
    ]
