# Generated by Django 4.1.5 on 2023-01-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calltime',
            old_name='show_id',
            new_name='show_id_id',
        ),
    ]
