# Generated by Django 4.1.5 on 2023-01-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shows',
            name='rehearsal_start',
            field=models.DateTimeField(),
        ),
    ]
