# Generated by Django 4.1.5 on 2023-01-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_rename_venue_calltime_venue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calltime',
            old_name='venue_id',
            new_name='venue',
        ),
    ]
