# Generated by Django 4.1.5 on 2023-01-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_shows_favorite_alter_shows_rehearsal_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('endtime', models.TimeField()),
                ('notes', models.TextField(null=True)),
                ('performers', models.ManyToManyField(to='getdata.performers')),
            ],
        ),
    ]
