# Generated by Django 4.1.5 on 2023-01-24 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0003_alter_shows_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltime',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getdata.company'),
        ),
        migrations.AlterField(
            model_name='rehearsalvenues',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getdata.company'),
        ),
    ]
