# Generated by Django 4.1.5 on 2023-01-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0003_calltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltime',
            name='starttime',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AlterField(
            model_name='calltime',
            name='date',
            field=models.DateField(),
        ),
    ]
