# Generated by Django 4.1.5 on 2023-01-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0004_rename_venue_calltime_venue_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('details', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
