# Generated by Django 4.1.5 on 2023-01-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0004_calltime_starttime_alter_calltime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltime',
            name='show',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='getdata.shows'),
        ),
        migrations.AddField(
            model_name='conflicts',
            name='endtime',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='calltime',
            name='starttime',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='roles',
            name='performer_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='getdata.performers'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='director_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='getdata.performers'),
        ),
    ]
