# Generated by Django 4.1.5 on 2023-01-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0005_alter_calltime_date_alter_calltime_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='rehearsal_start',
            field=models.DateField(default='1/1/2023'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='show_open',
            field=models.DateField(default='1/1/2023'),
        ),
    ]
