# Generated by Django 4.1.5 on 2023-01-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0006_alter_calltime_starttime_alter_conflicts_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltime',
            name='starttime',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='conflicts',
            name='endtime',
            field=models.DateTimeField(default='00:00:00'),
        ),
    ]
