# Generated by Django 4.1.5 on 2023-01-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0006_alter_shows_rehearsal_start_alter_shows_show_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
