# Generated by Django 4.1.5 on 2023-01-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0007_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performers',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rehearsalvenues',
            name='location',
            field=models.CharField(default='123 Fourth St.', max_length=128),
        ),
        migrations.AlterField(
            model_name='rehearsalvenues',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='shows',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
