# Generated by Django 4.1.5 on 2023-01-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0008_alter_performers_name_alter_rehearsalvenues_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsalvenues',
            name='name',
            field=models.CharField(default='Main Rehearsal Hall', max_length=128),
        ),
    ]
