# Generated by Django 4.1.5 on 2023-01-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0009_alter_calltime_starttime_alter_conflicts_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltime',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
