# Generated by Django 4.1.5 on 2023-01-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0010_alter_rehearsalvenues_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsalvenues',
            name='name',
            field=models.CharField(default='Rehearsal Room 1', max_length=128),
        ),
    ]
