# Generated by Django 4.1.5 on 2023-01-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0010_alter_calltime_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calltime',
            old_name='endtime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='calltime',
            old_name='show',
            new_name='show_id',
        ),
        migrations.RenameField(
            model_name='calltime',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
