# Generated by Django 4.1.5 on 2023-01-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0011_alter_rehearsalvenues_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performers',
            name='public_profile',
            field=models.IntegerField(default=0),
        ),
    ]
