# Generated by Django 4.1.5 on 2023-01-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0012_alter_performers_public_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performers',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
    ]
