# Generated by Django 4.1.5 on 2023-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0014_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltime',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calltime',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='calltime',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
