# Generated by Django 4.2.5 on 2024-04-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweetAbundance', '0003_remove_account_id_alter_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('color', models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='flavors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sweetAbundance.flavor'),
        ),
    ]
