# Generated by Django 4.2.5 on 2024-04-06 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweetAbundance', '0006_remove_product_id_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flavors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.AddField(
            model_name='flavor',
            name='product',
            field=models.ForeignKey(default='2oz Snickerdoodle Cookies by the Dozen', on_delete=django.db.models.deletion.CASCADE, to='sweetAbundance.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default='2oz Snickerdoodle Cookies by the Dozen', on_delete=django.db.models.deletion.CASCADE, to='sweetAbundance.product'),
            preserve_default=False,
        ),
    ]
