# Generated by Django 4.2.5 on 2024-04-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetAbundance', '0007_remove_product_flavors_remove_product_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
