# Generated by Django 4.2.5 on 2024-04-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetAbundance', '0009_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.JSONField(null=True),
        ),
    ]
