# Generated by Django 4.2.5 on 2024-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetAbundance', '0011_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small',
            field=models.BooleanField(default=True),
        ),
    ]
