"""empty message

Revision ID: 65522e3011ec
Revises: 
Create Date: 2022-12-15 15:07:24.657330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65522e3011ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('date_time', sa.DateTime(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('date_time'),
    sa.UniqueConstraint('date_time')
    )
    op.create_table('performers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('rehearsal_venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location'),
    sa.UniqueConstraint('name')
    )
    op.create_table('performers_conflicts',
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.Column('conflict_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conflict_date'], ['conflicts.date_time'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], ),
    sa.PrimaryKeyConstraint('performer_id', 'conflict_date')
    )
    op.create_table('shows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('rehearsal_start', sa.Date(), nullable=False),
    sa.Column('show_open', sa.Date(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['performers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_name', sa.String(length=128), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_name')
    )
    op.create_table('shows_venues',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['rehearsal_venues.id'], ),
    sa.PrimaryKeyConstraint('show_id', 'venue_id')
    )
    op.create_table('scenes_roles',
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('scene_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenes_roles')
    op.drop_table('shows_venues')
    op.drop_table('scenes')
    op.drop_table('roles')
    op.drop_table('shows')
    op.drop_table('performers_conflicts')
    op.drop_table('rehearsal_venues')
    op.drop_table('performers')
    op.drop_table('conflicts')
    # ### end Alembic commands ###
