name: Run tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests: 
    runs-on: ubuntu-latest

    steps:
      - name: Navigate to Sweet Abundance
        run: cd "Web Apps/sweetAbunance/sweetAbundance"
      - name: Django Test CI
        uses: UKnowWhoIm/django-test-action@v0.6.1
        with:
          settings-dir-path: "./"    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 16.18
      - name: Install Dependencies
        run: npm install package.json
      - name: Run Local Server
        run: python "Web Apps/sweetAbunance/sweetAbundance/manage.py" runserver
      - name: Run test file
        run: node puppeteer_test.js
