name: Run tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 16.18
      - name: Navigate to Sweet Abundance
        run: cd "Web Apps/sweetAbunance/sweetAbundance"
      - name: Install Dependencies
        run: npm install package.json
      - name: Build Django container
        run: |
          docker-compose up -d web
      - name: Run Django migrations
        run: |
          docker compose exec web python manage.py migrate
      - name: Run Django tests
        run: |
          docker compose exec web python manage.py runserver
      - name: Run test file
        run: node puppeteer_test.js
