name: Run tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests: 
    runs-on: ubuntu-latest
    env:
      DEBUG: True
      SECRET_KEY: secret
      ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_URL: sqlite:////tmp/db.sqlite3
      CORS_ORIGIN_WHITELIST: "http://localhost,http://127.0.0.1"
      CSRF_TRUSTED_ORIGINS: "http://localhost"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 16.18
      - name: Navigate to Sweet Abundance
        run: cd "Web Apps/sweetAbunance/sweetAbundance"
      - name: Install Dependencies
        run: npm install package.json
      - name: Install Django
        run: pip install django
      - name: Run Local Server
        run: python "Web Apps/sweetAbunance/sweetAbundance/manage.py" runserver
      - name: Run test file
        run: node puppeteer_test.js
